"""status table

Revision ID: 16818977054c
Revises: 425df6ebd6bd
Create Date: 2020-02-17 15:30:34.512941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16818977054c'
down_revision = '425df6ebd6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status')
    )
    op.add_column('tickets', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'status_id')
    op.drop_table('status')
    # ### end Alembic commands ###
