"""topic table

Revision ID: 2ca29be533f0
Revises: 68522c465015
Create Date: 2020-04-01 10:57:43.666143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca29be533f0'
down_revision = '68522c465015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.add_column('tickets', sa.Column('topics', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'topics', ['topics'], ['id'])
    op.drop_column('tickets', 'topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('topic', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'topics')
    op.drop_table('topics')
    # ### end Alembic commands ###
