"""Severity table

Revision ID: 425df6ebd6bd
Revises: a661378c9fd1
Create Date: 2020-02-17 14:00:44.426099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425df6ebd6bd'
down_revision = 'a661378c9fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('degree')
    )
    op.add_column('tickets', sa.Column('severity_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'severity', ['severity_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'severity_id')
    op.drop_table('severity')
    # ### end Alembic commands ###
