"""User table corrected and ticket table named

Revision ID: 5023ee817a86
Revises: af5019ebdf03
Create Date: 2020-02-10 10:18:54.856745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5023ee817a86'
down_revision = 'af5019ebdf03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_timestamp'), 'tickets', ['timestamp'], unique=False)
    op.drop_index('ix_ticket_timestamp', table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ticket_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ticket_pkey')
    )
    op.create_index('ix_ticket_timestamp', 'ticket', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_tickets_timestamp'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
