"""topic table create and column ticket for topic corrected

Revision ID: 68522c465015
Revises: dfa422bbaa4e
Create Date: 2020-04-01 10:41:08.546998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68522c465015'
down_revision = 'dfa422bbaa4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic')
    )
    op.create_foreign_key(None, 'tickets', 'topics', ['topic'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_table('topics')
    # ### end Alembic commands ###
