"""user-role link

Revision ID: ab7e2be148ef
Revises: c4ad57301e70
Create Date: 2020-02-23 10:53:10.426761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab7e2be148ef'
down_revision = 'c4ad57301e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tickets_role_id_fkey', 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'role_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('tickets', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tickets_role_id_fkey', 'tickets', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
