"""owner ticket field

Revision ID: beaf03025b4f
Revises: 1b553881284b
Create Date: 2020-02-11 20:04:08.565262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaf03025b4f'
down_revision = '1b553881284b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'owner_id')
    # ### end Alembic commands ###
