"""Role default removed

Revision ID: c98d8c9b20b9
Revises: ab7e2be148ef
Create Date: 2020-02-24 16:00:05.200407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c98d8c9b20b9'
down_revision = 'ab7e2be148ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roles_default', table_name='roles')
    op.drop_column('roles', 'default')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_index('ix_roles_default', 'roles', ['default'], unique=False)
    # ### end Alembic commands ###
