"""title ticket

Revision ID: e4cb8882c7bd
Revises: fd5cf5f78d8a
Create Date: 2020-02-14 09:51:48.731457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cb8882c7bd'
down_revision = 'fd5cf5f78d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('title', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'title')
    # ### end Alembic commands ###
