"""empty message

Revision ID: fd5cf5f78d8a
Revises: beaf03025b4f
Create Date: 2020-02-11 20:07:18.165848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5cf5f78d8a'
down_revision = 'beaf03025b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'owner_id')
    # ### end Alembic commands ###
